package com.bryancui.cbymod.entity.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.client.renderer.GlStateManager;
import org.lwjgl.opengl.GL11;

/**
 * ModelMagmaCube - Either Mojang or a mod author
 * Created using Tabula 7.0.0
 */
public class ModelBomb extends ModelBase {
    public ModelRenderer segments8;
    public ModelRenderer segments1;
    public ModelRenderer segments3;
    public ModelRenderer segments2;
    public ModelRenderer segments5;
    public ModelRenderer segments4;
    public ModelRenderer segments7;
    public ModelRenderer segments6;
    public ModelRenderer segments1_1;
    public ModelRenderer segments1_2;
    public ModelRenderer segments1_3;
    public ModelRenderer segments1_4;
    public ModelRenderer segments1_5;
    public ModelRenderer segments4_1;
    public ModelRenderer segments5_1;
    public ModelRenderer segments6_1;
    public ModelRenderer segments7_1;
    public ModelRenderer segments8_1;
    public ModelRenderer wingtop1;
    public ModelRenderer wingmid1;
    public ModelRenderer wingtail1;
    public ModelRenderer wingtop2;
    public ModelRenderer wingmid2;
    public ModelRenderer wingtail2;
    public ModelRenderer wingtop3;
    public ModelRenderer wingmid3;
    public ModelRenderer wingtail3;
    public ModelRenderer wingtop4;
    public ModelRenderer wingtop4_1;
    public ModelRenderer wingtop4_2;
    public ModelRenderer sign;
    public ModelRenderer segments1_6;
    public ModelRenderer segments1_7;
    public ModelRenderer segments1_8;
    public ModelRenderer segments7_2;
    public ModelRenderer segments7_3;

    public ModelBomb() {
        this.textureWidth = 64;
        this.textureHeight = 32;
        this.sign = new ModelRenderer(this, 0, 7);
        this.sign.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.sign.addBox(3.6F, 9.1F, -3.5F, 1, 7, 7, 0.0F);
        this.segments6 = new ModelRenderer(this, 0, 5);
        this.segments6.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.segments6.addBox(-4.0F, 21.0F, -4.0F, 8, 1, 8, 0.0F);
        this.segments1_5 = new ModelRenderer(this, 0, 0);
        this.segments1_5.setRotationPoint(-4.0F, 15.0F, -4.0F);
        this.segments1_5.addBox(0.0F, 0.0F, 0.0F, 8, 1, 8, 0.0F);
        this.wingtop4_1 = new ModelRenderer(this, 24, 0);
        this.wingtop4_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.wingtop4_1.addBox(-0.5F, 17.0F, -6.0F, 1, 1, 2, 0.0F);
        this.segments5 = new ModelRenderer(this, 0, 4);
        this.segments5.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.segments5.addBox(-4.0F, 20.0F, -4.0F, 8, 1, 8, 0.0F);
        this.segments7 = new ModelRenderer(this, 0, 6);
        this.segments7.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.segments7.addBox(-4.0F, 22.0F, -4.0F, 8, 1, 8, 0.0F);
        this.segments1 = new ModelRenderer(this, 0, 0);
        this.segments1.setRotationPoint(0.0F, -0.0F, 0.0F);
        this.segments1.addBox(-4.0F, 16.0F, -4.0F, 8, 1, 8, 0.0F);
        this.segments1_8 = new ModelRenderer(this, 0, 0);
        this.segments1_8.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.segments1_8.addBox(-4.0F, 9.0F, -4.0F, 8, 1, 8, 0.0F);
        this.wingmid1 = new ModelRenderer(this, 24, 0);
        this.wingmid1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.wingmid1.addBox(-6.0F, 17.0F, -0.5F, 2, 1, 1, 0.0F);
        this.wingtop4 = new ModelRenderer(this, 24, 0);
        this.wingtop4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.wingtop4.addBox(-0.5F, 16.0F, -5.0F, 1, 1, 1, 0.0F);
        this.segments2 = new ModelRenderer(this, 0, 1);
        this.segments2.setRotationPoint(0.0F, -0.0F, 0.0F);
        this.segments2.addBox(-4.0F, 17.0F, -4.0F, 8, 1, 8, 0.0F);
        this.segments7_2 = new ModelRenderer(this, 0, 6);
        this.segments7_2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.segments7_2.addBox(-4.0F, 4.0F, -4.0F, 8, 1, 8, 0.0F);
        this.wingtop2 = new ModelRenderer(this, 24, 0);
        this.wingtop2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.wingtop2.addBox(4.0F, 16.0F, -0.5F, 1, 1, 1, 0.0F);
        this.segments1_1 = new ModelRenderer(this, 0, 0);
        this.segments1_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.segments1_1.addBox(-4.0F, 12.0F, -4.0F, 8, 1, 8, 0.0F);
        this.segments7_3 = new ModelRenderer(this, 0, 6);
        this.segments7_3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.segments7_3.addBox(-4.0F, 3.0F, -4.0F, 8, 1, 8, 0.0F);
        this.segments8_1 = new ModelRenderer(this, 0, 7);
        this.segments8_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.segments8_1.addBox(-4.0F, 7.0F, -4.0F, 8, 1, 8, 0.0F);
        this.wingtail3 = new ModelRenderer(this, 24, 0);
        this.wingtail3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.wingtail3.addBox(-0.5F, 18.0F, 4.0F, 1, 6, 3, 0.0F);
        this.wingtail2 = new ModelRenderer(this, 24, 0);
        this.wingtail2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.wingtail2.addBox(4.0F, 18.0F, -0.5F, 3, 6, 1, 0.0F);
        this.wingtop4_2 = new ModelRenderer(this, 24, 0);
        this.wingtop4_2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.wingtop4_2.addBox(-0.5F, 18.0F, -7.0F, 1, 6, 3, 0.0F);
        this.wingmid3 = new ModelRenderer(this, 24, 0);
        this.wingmid3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.wingmid3.addBox(-0.5F, 17.0F, 4.0F, 1, 1, 2, 0.0F);
        this.segments6_1 = new ModelRenderer(this, 0, 5);
        this.segments6_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.segments6_1.addBox(-4.0F, 6.0F, -4.0F, 8, 1, 8, 0.0F);
        this.segments1_4 = new ModelRenderer(this, 0, 0);
        this.segments1_4.setRotationPoint(-4.0F, 14.0F, -4.0F);
        this.segments1_4.addBox(0.0F, 0.0F, 0.0F, 8, 1, 8, 0.0F);
        this.segments1_6 = new ModelRenderer(this, 0, 0);
        this.segments1_6.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.segments1_6.addBox(-4.0F, 11.0F, -4.0F, 8, 1, 8, 0.0F);
        this.segments5_1 = new ModelRenderer(this, 0, 4);
        this.segments5_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.segments5_1.addBox(-4.0F, 7.0F, -4.0F, 8, 1, 8, 0.0F);
        this.segments3 = new ModelRenderer(this, 24, 10);
        this.segments3.setRotationPoint(0.0F, -0.0F, 0.0F);
        this.segments3.addBox(-4.0F, 18.0F, -4.0F, 8, 1, 8, 0.0F);
        this.wingtop1 = new ModelRenderer(this, 24, 0);
        this.wingtop1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.wingtop1.addBox(-5.0F, 16.0F, -0.5F, 1, 1, 1, 0.0F);
        this.wingmid2 = new ModelRenderer(this, 24, 0);
        this.wingmid2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.wingmid2.addBox(4.0F, 17.0F, -0.5F, 2, 1, 1, 0.0F);
        this.wingtop3 = new ModelRenderer(this, 24, 0);
        this.wingtop3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.wingtop3.addBox(-0.5F, 16.0F, 4.0F, 1, 1, 1, 0.0F);
        this.segments1_2 = new ModelRenderer(this, 0, 0);
        this.segments1_2.setRotationPoint(-4.0F, 16.0F, -4.0F);
        this.segments1_2.addBox(0.0F, 0.0F, 0.0F, 8, 1, 8, 0.0F);
        this.segments4_1 = new ModelRenderer(this, 24, 19);
        this.segments4_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.segments4_1.addBox(-4.0F, 8.0F, -4.0F, 8, 1, 8, 0.0F);
        this.wingtail1 = new ModelRenderer(this, 24, 0);
        this.wingtail1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.wingtail1.addBox(-7.0F, 18.0F, -0.5F, 3, 6, 1, 0.0F);
        this.segments8 = new ModelRenderer(this, 0, 7);
        this.segments8.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.segments8.addBox(-4.0F, 23.0F, -4.0F, 8, 1, 8, 0.0F);
        this.segments7_1 = new ModelRenderer(this, 0, 6);
        this.segments7_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.segments7_1.addBox(-4.0F, 5.0F, -4.0F, 8, 1, 8, 0.0F);
        this.segments1_3 = new ModelRenderer(this, 0, 0);
        this.segments1_3.setRotationPoint(-4.0F, 13.0F, -4.0F);
        this.segments1_3.addBox(0.0F, 0.0F, 0.0F, 8, 1, 8, 0.0F);
        this.segments1_7 = new ModelRenderer(this, 0, 0);
        this.segments1_7.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.segments1_7.addBox(-4.0F, 10.0F, -4.0F, 8, 1, 8, 0.0F);
        this.segments4 = new ModelRenderer(this, 24, 19);
        this.segments4.setRotationPoint(0.0F, -0.0F, 0.0F);
        this.segments4.addBox(-4.0F, 19.0F, -4.0F, 8, 1, 8, 0.0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) { 
        this.sign.render(f5);
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.segments6.offsetX, this.segments6.offsetY, this.segments6.offsetZ);
        GlStateManager.translate(this.segments6.rotationPointX * f5, this.segments6.rotationPointY * f5, this.segments6.rotationPointZ * f5);
        GlStateManager.scale(0.7D, 1.0D, 0.7D);
        GlStateManager.translate(-this.segments6.offsetX, -this.segments6.offsetY, -this.segments6.offsetZ);
        GlStateManager.translate(-this.segments6.rotationPointX * f5, -this.segments6.rotationPointY * f5, -this.segments6.rotationPointZ * f5);
        this.segments6.render(f5);
        GlStateManager.popMatrix();
        this.segments1_5.render(f5);
        this.wingtop4_1.render(f5);
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.segments5.offsetX, this.segments5.offsetY, this.segments5.offsetZ);
        GlStateManager.translate(this.segments5.rotationPointX * f5, this.segments5.rotationPointY * f5, this.segments5.rotationPointZ * f5);
        GlStateManager.scale(0.8D, 1.0D, 0.8D);
        GlStateManager.translate(-this.segments5.offsetX, -this.segments5.offsetY, -this.segments5.offsetZ);
        GlStateManager.translate(-this.segments5.rotationPointX * f5, -this.segments5.rotationPointY * f5, -this.segments5.rotationPointZ * f5);
        this.segments5.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.segments7.offsetX, this.segments7.offsetY, this.segments7.offsetZ);
        GlStateManager.translate(this.segments7.rotationPointX * f5, this.segments7.rotationPointY * f5, this.segments7.rotationPointZ * f5);
        GlStateManager.scale(0.6D, 1.0D, 0.6D);
        GlStateManager.translate(-this.segments7.offsetX, -this.segments7.offsetY, -this.segments7.offsetZ);
        GlStateManager.translate(-this.segments7.rotationPointX * f5, -this.segments7.rotationPointY * f5, -this.segments7.rotationPointZ * f5);
        this.segments7.render(f5);
        GlStateManager.popMatrix();
        this.segments1.render(f5);
        this.segments1_8.render(f5);
        this.wingmid1.render(f5);
        this.wingtop4.render(f5);
        this.segments2.render(f5);
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.segments7_2.offsetX, this.segments7_2.offsetY, this.segments7_2.offsetZ);
        GlStateManager.translate(this.segments7_2.rotationPointX * f5, this.segments7_2.rotationPointY * f5, this.segments7_2.rotationPointZ * f5);
        GlStateManager.scale(0.4D, 1.0D, 0.4D);
        GlStateManager.translate(-this.segments7_2.offsetX, -this.segments7_2.offsetY, -this.segments7_2.offsetZ);
        GlStateManager.translate(-this.segments7_2.rotationPointX * f5, -this.segments7_2.rotationPointY * f5, -this.segments7_2.rotationPointZ * f5);
        this.segments7_2.render(f5);
        GlStateManager.popMatrix();
        this.wingtop2.render(f5);
        this.segments1_1.render(f5);
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.segments7_3.offsetX, this.segments7_3.offsetY, this.segments7_3.offsetZ);
        GlStateManager.translate(this.segments7_3.rotationPointX * f5, this.segments7_3.rotationPointY * f5, this.segments7_3.rotationPointZ * f5);
        GlStateManager.scale(0.2D, 1.0D, 0.2D);
        GlStateManager.translate(-this.segments7_3.offsetX, -this.segments7_3.offsetY, -this.segments7_3.offsetZ);
        GlStateManager.translate(-this.segments7_3.rotationPointX * f5, -this.segments7_3.rotationPointY * f5, -this.segments7_3.rotationPointZ * f5);
        this.segments7_3.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.segments8_1.offsetX, this.segments8_1.offsetY, this.segments8_1.offsetZ);
        GlStateManager.translate(this.segments8_1.rotationPointX * f5, this.segments8_1.rotationPointY * f5, this.segments8_1.rotationPointZ * f5);
        GlStateManager.scale(0.5D, 1.0D, 0.5D);
        GlStateManager.translate(-this.segments8_1.offsetX, -this.segments8_1.offsetY, -this.segments8_1.offsetZ);
        GlStateManager.translate(-this.segments8_1.rotationPointX * f5, -this.segments8_1.rotationPointY * f5, -this.segments8_1.rotationPointZ * f5);
        this.segments8_1.render(f5);
        GlStateManager.popMatrix();
        this.wingtail3.render(f5);
        this.wingtail2.render(f5);
        this.wingtop4_2.render(f5);
        this.wingmid3.render(f5);
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.segments6_1.offsetX, this.segments6_1.offsetY, this.segments6_1.offsetZ);
        GlStateManager.translate(this.segments6_1.rotationPointX * f5, this.segments6_1.rotationPointY * f5, this.segments6_1.rotationPointZ * f5);
        GlStateManager.scale(0.7D, 1.0D, 0.7D);
        GlStateManager.translate(-this.segments6_1.offsetX, -this.segments6_1.offsetY, -this.segments6_1.offsetZ);
        GlStateManager.translate(-this.segments6_1.rotationPointX * f5, -this.segments6_1.rotationPointY * f5, -this.segments6_1.rotationPointZ * f5);
        this.segments6_1.render(f5);
        GlStateManager.popMatrix();
        this.segments1_4.render(f5);
        this.segments1_6.render(f5);
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.segments5_1.offsetX, this.segments5_1.offsetY, this.segments5_1.offsetZ);
        GlStateManager.translate(this.segments5_1.rotationPointX * f5, this.segments5_1.rotationPointY * f5, this.segments5_1.rotationPointZ * f5);
        GlStateManager.scale(0.8D, 1.0D, 0.8D);
        GlStateManager.translate(-this.segments5_1.offsetX, -this.segments5_1.offsetY, -this.segments5_1.offsetZ);
        GlStateManager.translate(-this.segments5_1.rotationPointX * f5, -this.segments5_1.rotationPointY * f5, -this.segments5_1.rotationPointZ * f5);
        this.segments5_1.render(f5);
        GlStateManager.popMatrix();
        this.segments3.render(f5);
        this.wingtop1.render(f5);
        this.wingmid2.render(f5);
        this.wingtop3.render(f5);
        this.segments1_2.render(f5);
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.segments4_1.offsetX, this.segments4_1.offsetY, this.segments4_1.offsetZ);
        GlStateManager.translate(this.segments4_1.rotationPointX * f5, this.segments4_1.rotationPointY * f5, this.segments4_1.rotationPointZ * f5);
        GlStateManager.scale(0.9D, 1.0D, 0.9D);
        GlStateManager.translate(-this.segments4_1.offsetX, -this.segments4_1.offsetY, -this.segments4_1.offsetZ);
        GlStateManager.translate(-this.segments4_1.rotationPointX * f5, -this.segments4_1.rotationPointY * f5, -this.segments4_1.rotationPointZ * f5);
        this.segments4_1.render(f5);
        GlStateManager.popMatrix();
        this.wingtail1.render(f5);
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.segments8.offsetX, this.segments8.offsetY, this.segments8.offsetZ);
        GlStateManager.translate(this.segments8.rotationPointX * f5, this.segments8.rotationPointY * f5, this.segments8.rotationPointZ * f5);
        GlStateManager.scale(0.5D, 1.0D, 0.5D);
        GlStateManager.translate(-this.segments8.offsetX, -this.segments8.offsetY, -this.segments8.offsetZ);
        GlStateManager.translate(-this.segments8.rotationPointX * f5, -this.segments8.rotationPointY * f5, -this.segments8.rotationPointZ * f5);
        this.segments8.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.segments7_1.offsetX, this.segments7_1.offsetY, this.segments7_1.offsetZ);
        GlStateManager.translate(this.segments7_1.rotationPointX * f5, this.segments7_1.rotationPointY * f5, this.segments7_1.rotationPointZ * f5);
        GlStateManager.scale(0.6D, 1.0D, 0.6D);
        GlStateManager.translate(-this.segments7_1.offsetX, -this.segments7_1.offsetY, -this.segments7_1.offsetZ);
        GlStateManager.translate(-this.segments7_1.rotationPointX * f5, -this.segments7_1.rotationPointY * f5, -this.segments7_1.rotationPointZ * f5);
        this.segments7_1.render(f5);
        GlStateManager.popMatrix();
        this.segments1_3.render(f5);
        this.segments1_7.render(f5);
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.segments4.offsetX, this.segments4.offsetY, this.segments4.offsetZ);
        GlStateManager.translate(this.segments4.rotationPointX * f5, this.segments4.rotationPointY * f5, this.segments4.rotationPointZ * f5);
        GlStateManager.scale(0.9D, 1.0D, 0.9D);
        GlStateManager.translate(-this.segments4.offsetX, -this.segments4.offsetY, -this.segments4.offsetZ);
        GlStateManager.translate(-this.segments4.rotationPointX * f5, -this.segments4.rotationPointY * f5, -this.segments4.rotationPointZ * f5);
        this.segments4.render(f5);
        GlStateManager.popMatrix();
    }

    /**
     * This is a helper function from Tabula to set the rotation of model parts
     */
    public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }
}
